DROP TABLE "test";

BEGIN;
CREATE TABLE "test"();

ALTER TABLE "test" ADD COLUMN id SMALLINT;
ALTER TABLE "test" ADD COLUMN tester BOOLEAN DEFAULT FALSE;

COMMIT;


INSERT INTO "test" (id) VALUES (1);

SELECT * FROM test;
