[Versions]

[Protocols]

[GroupedActivities]
protocols = ('protocol_id', 'protocol_id')
versions = ('archive_version_id', 'version_id')

[TeamMembers]

[N2kHabTypes]

[N2kHabStrata]
n2khabtypes = ('n2khabtype_id', 'n2khabtype_id')

[Locations]

[LocationCells]
locations = ('location_id', 'location_id')

[Coordinates]
locations = ('location_id', 'location_id')

[LocationInfos]
locations = ('location_id', 'location_id')

[LocationJournals]
locations = ('location_id', 'location_id')

[SampleUnits]
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[SampleUnitPolygons]
sampleunits = ('sampleunit_id', 'sampleunit_id')

[Replacements]
sampleunits = ('sampleunit_id', 'sampleunit_id')

[ReplacementCells]
replacements = ('replacement_id', 'replacement_id')

[MHQPolygons]
locations = ('location_id', 'location_id')

[LocationAssessments]
sampleunits = ('sampleunit_id', 'sampleunit_id')
locations = ('location_id', 'location_id')

[FieldCalendars]
sampleunits = ('sampleunit_id', 'sampleunit_id')
teammembers = ('teammember_assigned', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[Visits]
fieldcalendars = ('fieldcalendar_id', 'fieldcalendar_id')
sampleunits = ('sampleunit_id', 'sampleunit_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[OtherVisits]
fieldcalendars = ('fieldcalendar_id', 'fieldcalendar_id')
sampleunits = ('sampleunit_id', 'sampleunit_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[AquaticTypesVisits]
fieldcalendars = ('fieldcalendar_id', 'fieldcalendar_id')
sampleunits = ('sampleunit_id', 'sampleunit_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[TerrestrialTypesVisits]
fieldcalendars = ('fieldcalendar_id', 'fieldcalendar_id')
sampleunits = ('sampleunit_id', 'sampleunit_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[TargetPoints]

[ExtraLocevals]

[CellMaps]

[FreeFieldNotes]
teammembers = ('teammember_id', 'teammember_id')

[Trails]

[ReplacementArchives]
versions = ('version_id', 'version_id')

