#+title: Steps Journal
#+author: Falk Mielke

This file documents the steps I undertook to set up the MNE database structure.

* General
** server setup
SCHEDULED: <2025-05-31 Sat>

+ set up the SQL server on a web hosting service
+ running on arch linux; super user and normal user
+ access via =ssh=:
    + =ssh -p <port> <normaluser>@<host-ip>=
+ postgres database initialized and postgis installed

full details: [[https://github.com/falkmielke/agenda/blob/main/notes/20250602135718-inbopostgis.org]]

#+begin_quote
*Currently, each new IP must be registered in* =/var/lib/postgres/data/pg_hba.conf= *to be able to connect to the database.*
#+end_quote
/cf./ [[https://wiki.archlinux.org/title/PostgreSQL#Optional_configuration]]

** sql user management
SCHEDULED: <2025-05-31 Sat>

... is done directly on the server.

#+begin_src sh :eval no
ssh -p <port> <normaluser>@<host-ip>
su - root
su - postgres
createuser -p <port> --interactive

psql -p <port>
# ALTER USER <user> WITH ENCRYPTED PASSWORD '<password>';
#+end_src

new username needs to be added to =pg_hba.conf=!


** database setup
SCHEDULED: <2025-06-02 Mon>

connect (ssh via keys):
#+begin_src sh :eval no
ssh -p <port> <normaluser>@<host-ip>
su - root
su - postgres
#+end_src


drop-create:
#+begin_src sh :eval no
# dropdb <database> -p <port>
createdb <database> -O <owner> -p <port>
#+end_src


postgis extension:

#+begin_src sh :eval no
psql -U <owner> -h <host-ip> -p <port> -d <database> -W
#+end_src

#+begin_src sql :eval no
\c <database>
CREATE EXTENSION postgis;
CREATE EXTENSION postgis_topology;
CREATE EXTENSION fuzzystrmatch;
CREATE EXTENSION postgis_tiger_geocoder;

#+end_src


** database structure
SCHEDULED: <2025-06-02 Mon>-<2025-06-05 Thu>

A python script is available here:
+ =n2khab-mne-monitoring/900_database_organization/GenerateDatabase.py=

This ideally uses a virtual environment, set up as follows:
#+begin_src sh :eval no
cd <project_folder>
python -m venv .dbinit
source .dbinit/bin/activate
pip install --upgrade pip
pip install --upgrade -r python_requirements.txt
# pip freeze > python_requirements.txt # to feed back updated requirements
#+end_src


Then to run it, with a database connection config file (as described in the script) in place:
#+begin_src sh :eval no
source .dbinit/bin/activate
# python GenerateDatabase.py
python 020_create_databases.py
#+end_src


The script works on "=csv="s which have a fixed structure to define shema's, tables, columns.

An example google file can be found [[https://docs.google.com/spreadsheets/d/1BTtG-A2ASjbF7IhYYb8FDcQLBZtSQbLbElUUYeofHNM/edit?usp=drive_link][here]],
+the =csv='s are generated by "File >> Download >> Comma Separated Values (.csv)" for each sheet in the document.+
the =csv='s are generated by "File >> Download >> OpenDocument (.ods)" which can be converted to =.csv= with the =ODStoCSVs= python function.
Those comma separated text files are stored in the =db_structure= subfolder.


Because tables and roles are organized in schema's,
it might be necessary to
#+begin_src sql
SET search_path TO public,<schema>;
SHOW search_path;
-- \dt+
#+end_src



* Biotieker, outbound

** setup database
SCHEDULED: <2025-06-05 Thu>

| database name | loceval          |
| schema        | loceval_outbound |
| peer user     | Ward             |

#+begin_src sh :eval no
psql -h <host> -p <port> -U <user> -d <database> -W
#+end_src

** location/activity calendar
SCHEDULED: <2025-06-05 Thu>

*goal:*
+ get a table with point geometry of sample target locations to the database
+ options to filter by date, potentially FAs, ...

Database creation in [[file:020_create_databases.py]]
Gradual refinement in [[file:100_sample_location_tests.qmd][100_sample_location_tests.qmd]]

TODO:
+ [X] =n2khab_data/10_raw/grtsmaster_habitats= issue: =n2khab::read_GRTSmh()= requires capitals -> was my fault
+ [X] =loceval_outbound=: =Calendar= links to =ActivityGroups=, but not to =ActivitySequences=?
  -> the sequence is in the dates.


** ODS download and conversion
SCHEDULED: <2025-06-06 Fri>

It is now possible to *download the google sheet as ODS* and convert it to csv automatically.

** constraints
SCHEDULED: <2025-06-06 Fri>

The option to specify constraints was added.
More info here: [[https://www.postgresql.org/docs/current/ddl-constraints.html]]

Most useful are
+ =UNIQUE= (e.g. for columns which are pk, but blocked by geometry fid)
+ value ranges, e.g. =CHECK (year > 0)=.


** multiple schemas
SCHEDULED: <2025-06-06 Fri>

In- and outbound schemas can be defined within the same file.
foreign keys across schema's are possible.


** pgmodeler import
SCHEDULED: <2025-06-06 Fri>

[[https://pgmodeler.io]]

A great tool to visualize relational databases.

It crashed earlier on syncing the "Plantentuin" pilot project,
but it worked fine now for importing the database and visualizing relations.

Will be re-used ad hoc later.

** sequence issues
SCHEDULED: <2025-06-06 Fri>

Due to a misconfiguration, qgis attempts to create a new location id upon attribute save.

Added an "=EXPOST=" sheet to run after succesful creation.
#+begin_src sql
GRANT USAGE ON SEQUENCE "loceval_outbound"."seq_locationcalendar_id" TO ward;
#+end_src

/update:/ Because this was such a common issue, the GRANT USAGE is now integrated for all sequences.

(sequences can be listed with =\ls+=)

** binaries, images, BLOB
SCHEDULED: <2025-06-06 Fri>

Managed to upload a binary with qgis.
Will require download/restoration tests and good disk space management.

** Visits
SCHEDULED: <2025-06-06 Fri>
a derived table showing a subset of the calendar

** stratum et al. to Location Calendar
SCHEDULED: <2025-06-10 Tue>

+ used an upstream object of =fag_grts_calendar_...= to have scheme/stratum/module/panel for calendar
+ TODO: some locations were not unique

#+begin_src R
  fag_stratum_grts_calendar_2025_attribs_sf %>%
    select(
      scheme,
      module_combo_code,
      panel_set,
      stratum,
      targetpanel,
      field_activity_group,
      grts_address_final,
      date_start
    )
#+end_src


** Schema Re-Organisation
SCHEDULED: <2025-06-10 Tue>

We now use simple names:
+ metadata
+ outbound
+ inbound

separation is based on user rights and purpose


** TeamMembers
SCHEDULED: <2025-06-10 Tue>

to refer to users who upload stuff


** N2kHabTypes
SCHEDULED: <2025-06-10 Tue>

reference to habitat types and strata
+ adding =stratum_to_expect= to LocCal
+ adding =stratum_assigned= to =Visits=


** Activities - overhaul
SCHEDULED: <2025-06-11 Wed>

Some changes and discussions with Floris about the "Activities" logic.

+ removed =ActivityGroups= and =ActivitySequences=
  + sequences are already included in the calendar data via =rank=
+ ... for the sake of =GroupedActivities=
  + contains activities in different groups
+ link to calendar via =grouped_activity_id=
  + and sequence determined by =activity_sequence=
  + =LocationCalendar= and =Visits= will have multiple lines now (all scheduled activities per visit)
  + will have to see how this plays out in qgis.


*** chat protocol
You, 9:50 AM
#+begin_quote
FYI er zijn activities die niet in een activity sequence terecht komen:

    activities %>%
      anti_join(
      activity_sequences,
      join_by(activity)
    )

->
    activity         activity_name        is_datacollection_me…¹ is_field_activity
    <fct>            <fct>                <lgl>                  <lgl>
    1 GWSURFINSTALLMAT installatiemateriaa… FALSE                  FALSE
    2 GWMAT            staalnamemateriaal … FALSE                  FALSE
    3 SOILMAT          staalnamemateriaal … FALSE                  FALSE
    4 SURFMAT          staalnamemateriaal … FALSE                  FALSE
    5 SECDATACOLL      data uit bestaande … TRUE                   FALSE
    # ℹ abbreviated name: ¹ is_datacollection_method
    # ℹ 3 more variables: is_prep_activity <lgl>, is_lab_activity <lgl>,
    #   protocol <fct>

... maar het zijn maar vijf; geen "field" activities; ik veronderstel dat ze niet in de calender terecht komen.
Ik ga ze toch meenemen naar de databank, voor de app oplossen door een "fake sequence" met naam van de activity toe te kennen, maar later kijken of ze er in qgis verschijnen of niet.
#+end_quote

Floris Vanderhaeghe, 9:51 AM
#+begin_quote
Klopt. Je hebt die zaken niet nodig, enkel de locatie-attributen en de veldwerkkalender. Ik had ze niet toegevoegd als element van de data, maar ivm tonen van inhoudelijke samenhang tussen field activities. Als je gewoon activity_sequences gaat joinen aan activities, verwacht ik dat je er te veel gaat krijgen. Cf semi-joins hieronder, die ze filteren, en conditioneel stellen aan module en scheme. Puur achtergrond!

    faseqs <- [...]
    faseqs_fag_fa <- [...]
#+end_quote

You, 9:54 AM
#+begin_quote
Ja, precies bij die semi-joins was ik begonnen :)
Het "te veel krijgen" is voor activities niet het gevaar, maar een activity of groep missen die later niet in de metadata-tabel staat kan de databank-logica crashen ivm. "NOT NULL"-constraints.
En ook voorbereidend desktop-werk zou in de app als een "Notitie"-laag meegevoerd kunnen worden, met een link naar een "activity".
Daarom wil ik ze er liever allemaal mee hebben.
#+end_quote

Floris Vanderhaeghe, 10:03 AM, Edited
#+begin_quote
Snap ik wel vanuit databankopzicht, maar volgens mij hebben de activity sequences geen toegevoegde meerwaarde voor de uitvoerder op terrein, tov de kalender + rank. Achterwege laten is dus volgens mij even goed. Niet alles uit de POC hoeft in een databank lijkt me. Niet dat het niet mag natuurlijk.

Wat wel relevant is, is om 'overdue' taken te markeren en te prioriteren, als die op dezelfde locatie en voor hetzelfde stratum al hadden moeten gebeuren tov de daar geplande taken in een huidig datuminterval taak te kunnen uitvoeren. Met andere woorden, omgaan met veldwerkvertraging op een locatie (grts_address) x stratum, op basis van datuminterval en rank. We laten niets 'achter', vertraagde zaken zijn prioritairder en blijven op de planning staan.

Let er ook op dat field acts in eenzelfde FAG uitgevoerd moeten worden tijdens eenzelfde bezoek. Dat is de reden waarom FAG de eenheid is van de veldwerkkalender.

Wellicht vertel ik hier niets nieuws 🙂
#+end_quote

You, 10:13 AM
#+begin_quote
> hebben de activity sequences geen toegevoegde meerwaarde
klopt, maar activity_sequences is de enige variabele waarin ik group en activity samen vindt. Mijn bericht boven was maar een "check", want ik begin uiteraard bij de activities tabel.

> Wat wel relevant is, is om 'overdue' taken te markeren en te prioriteren
Inderdaad, dit komt er in.

> field acts in eenzelfde FAG uitgevoerd moeten worden tijdens eenzelfde bezoek
Ja, zo ga ik het ook implementeren. Ward krijgt een takenlijst, met takengroepen en onderstappen.
#+end_quote

Floris Vanderhaeghe, 10:17 AM
#+begin_quote
Goed, merci!
#+end_quote



** qgis refresher
SCHEDULED: <2025-06-11 Wed>

qgis startup recently began to throw some python errors

#+begin_src python
from osgeo import gdal, ogr, osr
#+end_src


** postgres VIEWs
SCHEDULED: <2025-06-11 Wed>

working on the database from qgis would cause confusion with all the unused, technical fields.
Views are a great way out.

#+begin_src sql
DROP VIEW IF EXISTS "outbound"."TestView";
CREATE VIEW "outbound"."TestView" AS
SELECT
    ogc_fid,
    wkb_geometry,
    locationcalendar_id,
    stratum,
    teammember_assigned,
    stratum_to_expect,
    date_start,
    date_end,
    visit_planned,
    notes
FROM "outbound"."LocationCalendar";
#+end_src

Views are now part of the database definition.
I tested that notes can be stored back to the database. HOORAY!


** TODO Data Captation
SCHEDULED: <2025-06-16 Mon>

*The database =loceval= is transient.*
Data prepared at home or generated in the field must be captured and moved to a completely different database: =mnmdb=.
+ =LocationCalendar= is augmented and changed dynamically -> append diffs to =mnmdb=
+ =Visits= have a field to indicate they are done, but should be moved/pruned regularly
+ =FieldNotes= must be stored irrespective of the =hide= tag; images linked and moved to storage


** TODO CONCEPT
SCHEDULED: <2025-06-16 Mon>

+ [X] will require additional schema's (=metadata=, e.g. for =username=, =activity_groups=, or sequences) and =outbound=/=inbound= database schemes
+ [ ] database mirrors (=loceval_dev= / =loceval=)
