---
title: "Sample Unit Overview"
date: today
format:
  html:
    toc: true
    html-math-method: katex
    code-fold: false
    embed-resources: true
  pdf:
    toc: false
    margin-left: 1cm
    margin-top: 1cm
    margin-rechts: 1cm
    margin-bottom: 1cm
knitr:
  opts_chunk:
    echo: false
---



```{r libraries}

source("MNMLibraryCollection.R")
load_database_interaction_libraries()

source("MNMDatabaseConnection.R")
source("MNMDatabaseToolbox.R")

# credentials are stored for easy access
config_filepath <- file.path("./inbopostgis_server.conf")

suffix <- "-staging" # "-testing"
suffix <- ""
```


-- choose a GRTS

```{r choose-grts}
grts <- c(1205598, 41313630) # replacement cell missing from updated plans
    # c(23238, 6314694, 23091910) # Hellebos!
    # c(908981) # dismissed -> no replacements
    # c(3554997, 29769397) # early bird ZEB/achterhaven
    # c(5193397, 57919349) # LOST?!
    # c(84598, 871030) # replacement mishap
    # c(1999406, 6417454)
    # c(53206450) # victim to the Dolle Dromedaris
    # c(13688242) # victim to the Dolle Dromedaris
    # c(53662, 4772254) # victim to the Dolle Dromedaris
    # c(41313630) # installed location, not planned anymore
    # c(23238, 6314694, 23091910) # Hellebos!
    # c(49896893, 21323197)

    # c(1902553) # info INST op foute regel (planning oud: 2025-10-01; nieuw: 2025-07-01)
    # c(6092977) # info INST on wrong row

    # c(3554997, 29769397)
    # c(5234357, 19914421)
    # c(5193397, 59719349) # left-over WIA
    # SELECT * FROM "inbound"."WellInstallationActivities" WHERE grts_address = 59719349;
    # UPDATE "inbound"."WellInstallationActivities" SET grts_address = 59719349 WHERE grts_address = 5193397;

    # c(4163858, 29329682)
    # c(415022, 3560750)
    # c(122549)
    # c(49896893, 21323197) # "Putten West"; disappeared with POC update 0.14 (TODO)
    # c(3554997, 29769397)
    # c(51221550, 16470006) # WIA/CSA mismatch 20251016 -> special activities seem missed on replacement processing (091_)
    # c(120110) # dual replacement
    # c(23257, 60185305) # visit by Wouter 20/8
    # c(1920534) # cell lost upon update loceval
    # c(2136622, 1677870)
    # c(53438326, 57632630)
    # c(437685, 8826293)
    # c(24774)
    # c(1280278)
    # c(23238, 23091910, 6314694) # Hellebos
    # c(4761777)
    # c(23238)
    # c(10119474) # this is only LOCEVAL <- SURF_03.4_lentic
    # c(1202926, 10640110) more missed archives
    # c(219694, 9525806) # was partially replaced and therefore archived
    # c(1999406, 6417454) # was falsely archived
    # c(31496054)
    # c(219694)

```


# LOCEVAL: `r as.character(grts)`

```{r connect-loceval}
database_label <- "loceval"

### connect to database
mnmdb <- connect_mnm_database(
  config_filepath,
  database_mirror = glue::glue("{database_label}{suffix}"),
  user = "monkey",
  password = NA
)
# keyring::keyring_delete(keyring = "mnmdb_temp")
message(mnmdb$shellstring)

```



```{r helper-join-activity-groups-loceval}

join_activity_groups <- function(df) {
  df %>% dplyr::left_join(
      mnmdb$query_columns(
        "GroupedActivities",
        c(
          "activity_group_id",
          "activity_group"
        )
      ) %>% dplyr::distinct(),
      by = dplyr::join_by(activity_group_id)
    ) %>%
  return()
}

```


```{r sample-units}

sunit <- mnmdb$query_table("SampleUnits") %>%
  filter(grts_address %in% grts)


loc_ids <- mnmdb$pull_column("Locations", "location_id")
loc_cells <- mnmdb$pull_column("LocationCells", "location_id")
loc_infos <- mnmdb$pull_column("LocationInfos", "location_id")

sunit <- sunit %>%
  mutate(
    has_loc = location_id %in% loc_ids,
    has_cell = location_id %in% loc_cells,
    has_infos = location_id %in% loc_infos,
    archived = isFALSE(is.na(archive_version_id))
  )

eva_print_sunit <- function() {
  sunit %>%
    dplyr::rename(
      suid = sampleunit_id,
      lid = location_id,
      replaced = is_replaced,
      mhq = in_mhq_samples,
      forest = is_forest,
      typ_weg = type_is_absent,
      grts = grts_address
    ) %>%
    dplyr::select(
      grts,
      type,
      domain_part,
      schemes,
      lid,
      suid,
      replaced,
      has_loc,
      has_cell,
      has_infos,
      mhq,
      forest,
      typ_weg,
      archived
    ) %>%
    t() %>% 
    knitr::kable()
}

```


```{r loceval-ofos}

ofos <- mnmdb$query_table("LocationAssessments") %>%
  filter(grts_address %in% grts)

eva_print_ofos <- function() {
  ofos %>%
    dplyr::rename(
      lid = location_id,
      suid = sampleunit_id,
      grts = grts_address,
      dis = cell_disapproved,
      done_a = assessment_done
    ) %>%
    arrange(type, dis, done_a) %>% 
    dplyr::select(
      suid,
      grts,
      type,
      dis,
      done_a
    ) %>%
    knitr::kable()
}

```


```{r loceval-calendar}

facal <- mnmdb$query_table("FieldActivityCalendar") %>%
  filter(grts_address %in% grts) %>%
  join_activity_groups() # %>%

eva_print_facal <- function() {
  facal %>%
    dplyr::rename(
      fcid = fieldactivitycalendar_id,
      suid = sampleunit_id,
      agid = activity_group_id,
      archv = archive_version_id,
      done_p = done_planning,
      no_vis = no_visit_planned
    ) %>%
    dplyr::select(
      type,
      suid,
      fcid,
      agid,
      activity_group,
      date_start,
      archv,
      no_vis,
      done_p
    ) %>%
    arrange(type, date_start, agid) %>% 
    knitr::kable()
}

```

```{r loceval-visits}

visits <- mnmdb$query_table("Visits") %>%
  filter(grts_address %in% grts) %>%
  join_activity_groups()

eva_print_visits <- function() {
  visits %>%
    dplyr::rename(
      grts = grts_address,
      lid = location_id,
      suid = sampleunit_id,
      agid = activity_group_id,
      fcid = fieldactivitycalendar_id,
      archv = archive_version_id,
      vid = visit_id
    ) %>%
    dplyr::select(
      grts,
      type,
      lid,
      suid,
      fcid,
      vid,
      agid,
      date_start,
      archv,
      date_visit
    ) %>%
    arrange(type, date_start, agid) %>% 
    knitr::kable()
}

```


```{r loceval-infos}

infos <- mnmdb$query_table("LocationInfos") %>%
  filter(grts_address %in% grts)

eva_print_infos <- function() {
  infos %>%
    dplyr::rename(
      grts = grts_address,
      liid = locationinfo_id,
      lid = location_id,
      inaccess = accessibility_inaccessible,
      hints = recovery_hints
    ) %>%
    dplyr::select(
      liid,
      grts,
      lid,
      inaccess,
      hints
    ) %>%
    knitr::kable()
}

```


```{r loceval-replacements}

replacements <- mnmdb$query_table("Replacements") %>%
  filter(grts_address %in% grts)

eva_print_replacements <- function() {
  replacements %>%
    dplyr::rename(
      grts = grts_address,
      typ = type,
      suid = sampleunit_id,
      rep = grts_address_replacement,
      rank = replacement_rank,
      sel = is_selected,
      tsug = type_suggested
    ) %>%
    dplyr::select(
      grts,
      typ,
      rank,
      rep,
      sel,
      tsug
    ) %>%
    knitr::kable()
}

```



```{=latex} 
\pagebreak 
```

## sample units
```{r eva-print-sunit}
#| echo: false
eva_print_sunit()
```

## ofos
```{r eva-print-ofos}
#| echo: false
eva_print_ofos()
```

## field activities
```{r eva-print-cal}
#| echo: false
eva_print_facal()
```

```{r eva-print-visits}
#| echo: false
eva_print_visits()
```

## infos
```{r eva-print-infos}
#| echo: false
eva_print_infos()
```

## replacements
```{r eva-print-replacements}
#| echo: false
eva_print_replacements()
```


```{=latex} 
\pagebreak 
```

# MNMGWDB: `r as.character(grts)`

```{r noop}
#| eval: false
#| echo: false
# source('080_connected_by_GRTS.R')
```

```{r database-connection}
database_label <- "mnmgwdb"

### connect to database
mnmdb <- connect_mnm_database(
  config_filepath,
  database_mirror = glue::glue("{database_label}{suffix}"),
  user = "monkey",
  password = NA
)
# keyring::keyring_delete(keyring = "mnmdb_temp")
message(mnmdb$shellstring)

```

-- helpers

```{r helper-join-activity-groups}

join_activity_groups <- function(df) {
  df %>% dplyr::left_join(
      mnmdb$query_columns(
        "GroupedActivities",
        c(
          "activity_group_id",
          "activity_group"
        )
      ) %>% dplyr::distinct(),
      by = dplyr::join_by(activity_group_id)
    ) %>%
  return()
}

```


```{r helper-query-special_activities}

query_special_activity <- function(shorthand) {

  if (shorthand == "WIA") {
    table_label <- "WellInstallationActivities"
  } else if (shorthand == "CSA") {
    table_label <- "ChemicalSamplingActivities"
  }

  mnmdb$query_columns(
    table_label,
    c(
      "fieldwork_id",
      "samplelocation_id",
      "fieldworkcalendar_id",
      "visit_id",
      "grts_address",
      "stratum",
      "activity_group_id",
      "date_start"
    )
  ) %>%
  dplyr::mutate(act = shorthand) %>%
  return()
}

```


-- The Backbone: Sample Unit // Sample Location

```{r sample-locations}

slocs <- mnmdb$query_table("SampleLocations") %>%
  filter(grts_address %in% grts)


loc_ids <- mnmdb$pull_column("Locations", "location_id")
loc_cells <- mnmdb$pull_column("LocationCells", "location_id")
loc_infos <- mnmdb$pull_column("LocationInfos", "location_id")

slocs <- slocs %>%
  mutate(
    has_loc = location_id %in% loc_ids,
    has_cell = location_id %in% loc_cells,
    has_infos = location_id %in% loc_infos,
    archived = isFALSE(is.na(archive_version_id))
  )

gw_print_slocs <- function() {
  slocs %>%
    dplyr::rename(
      slid = samplelocation_id,
      lid = location_id,
      replaced = is_replacement,
    ) %>%
    dplyr::select(
      grts_address,
      strata,
      domain_part,
      schemes,
      lid,
      slid,
      replaced,
      has_loc,
      has_cell,
      has_infos,
      archived
    ) %>%
    t() %>% 
    knitr::kable()
}

```


-- The Work: Calendar and Visits

```{r fieldwork-calendar}

fwcal <- mnmdb$query_table("FieldworkCalendar") %>%
  filter(grts_address %in% grts) %>%
  join_activity_groups() # %>%
  # left_join(
  #   mnmdb$query_table("Visits"),
  #   by = join_by(fieldworkcalendar_id),
  #   suffix = c("", "_vis")
  # )

gw_print_fwcal <- function() {
  fwcal %>%
    dplyr::rename(
      fcid = fieldworkcalendar_id,
      slid = samplelocation_id,
      agid = activity_group_id,
      archv = archive_version_id,
      done_p = done_planning
    ) %>%
    dplyr::select(
      stratum,
      slid,
      fcid,
      agid,
      activity_group,
      date_start,
      archv,
      # teammember_assigned,
      # date_visit_planned,
      done_p
    ) %>%
    arrange(stratum, date_start, agid) %>% 
    knitr::kable()
}

```

```{r visits}

visits <- mnmdb$query_table("Visits") %>%
  filter(grts_address %in% grts) %>%
  join_activity_groups()

gw_print_visits <- function() {
  visits %>%
    dplyr::rename(
      grts = grts_address,
      lid = location_id,
      slid = samplelocation_id,
      agid = activity_group_id,
      fcid = fieldworkcalendar_id,
      archv = archive_version_id,
      vid = visit_id,
      tid = teammember_id
    ) %>%
    dplyr::select(
      grts,
      stratum,
      lid,
      slid,
      fcid,
      vid,
      agid,
      date_start,
      archv,
      tid,
      issues,
      date_visit
    ) %>%
    arrange(stratum, date_start, agid) %>% 
    knitr::kable()
}

```



```{r special-activities}

activities <- bind_rows(
    query_special_activity("WIA"),
    query_special_activity("CSA")
  ) %>%
  filter(grts_address %in% grts) %>%
  join_activity_groups()

gw_print_special_activities <- function() {
  activities %>%
    dplyr::rename(
      grts = grts_address,
      slid = samplelocation_id,
      agid = activity_group_id,
      fcid = fieldworkcalendar_id,
      fwid = fieldwork_id,
      vid = visit_id,
    ) %>%
    dplyr::select(
      act,
      fwid,
      grts,
      stratum,
      fcid,
      vid,
      agid,
      date_start
    ) %>%
    arrange(stratum, date_start, agid) %>% 
    knitr::kable()
}

```


```{r location-infos}

infos <- mnmdb$query_table("LocationInfos") %>%
  filter(grts_address %in% grts)

gw_print_infos <- function() {
  infos %>%
    dplyr::rename(
      grts = grts_address,
      liid = locationinfo_id,
      lid = location_id,
      inaccess = accessibility_inaccessible,
      hints = recovery_hints,
      tina1 = watina_code_1,
      tina2 = watina_code_2
    ) %>%
    dplyr::select(
      liid,
      grts,
      lid,
      inaccess,
      hints,
      tina1,
      tina2
    ) %>%
    knitr::kable()
}
```



```{r gw-replacements}


repdat <- mnmdb$query_table("ReplacementData") %>%
  filter((grts_address %in% grts) | (grts_address_replacement %in% grts))

gw_print_replacement <- function() {
  repdat %>%
    dplyr::rename(
      grts = grts_address,
      rep = grts_address_replacement,
      slid = new_samplelocation_id,
      sel = is_replaced
    ) %>%
    dplyr::select(
      grts,
      type,
      rep,
      slid,
      sel
    ) %>%
    knitr::kable()
}

```



```{=latex} 
\pagebreak 
```

## sample location

```{r print-sloc}
#| echo: false
gw_print_slocs()
```


## calendar

```{r print-fwcal}
#| echo: false
gw_print_fwcal()
```


## visits

```{r print-visit}
#| echo: false
gw_print_visits()
```

special activities (well installation, chem sampling)

```{r print-special-activities}
#| echo: false
gw_print_special_activities()
```

## location infos

```{r print-infos}
#| echo: false
gw_print_infos()
```

## replacement
```{r print-replacements}
#| echo: false
gw_print_replacement()
```

