
# poor man's OOP: the database connection list object
# supposed to be loaded prior to "DatabaseToolbox"

#_______________________________________________________________________________
### TABLE OF CONTENTS




#_______________________________________________________________________________
### STRUCTURE

#' Read a table relation config file and convert it to data frame.
#'
#' Database structure is generated from a spreadsheet document. There is one
#' special file which stores the database structure, i.e. the relations of
#' tables to each other. It is generated by the adjacent Python scripts and read
#' in via `configr`. This function helps to load that relations file.
#'
#' @param storage_filepath the path to the config file
#'
#' @return data frame with the column relations from a dependent to a relation
#'     table. Note that relation table names are lowercase due to some
#'     ConfigParser limitation.
#'
#' @examples
#' \dontrun{
#'   read_table_relations_config(
#'     storage_filepath = file.path(
#'       "./devdb_structure/table_relations.conf"
#'   ))
#' }
#'
read_table_relations_config <- function(storage_filepath) {

  stopifnot("configr" = require("configr"))

  # read the raw file
  table_relations <- configr::read.config(file = storage_filepath)

  # Initialize empty. What a humble procedure.
  relation_lookup <- data.frame(
    relation_table = character(),
    dependent_table = character(),
    dependent_column = character(),
    relation_column = character()
  )

  # oh, how I miss my dictionaries!
  for (deptab in attributes(table_relations)[[1]]) {
    for (reltab in attributes(table_relations[[deptab]])$names){
      if(is.null(table_relations[[deptab]][reltab])) next
      new_row <- c(
        reltab,
        deptab,
        eval(parse(text = sprintf("c%s", table_relations[[deptab]][[reltab]])))
      )
      relation_lookup <- dplyr::bind_rows(
        relation_lookup,
        setNames(new_row, names(relation_lookup))
      )
    }
  }

  # knitr::kable(relation_lookup)
  return(relation_lookup)

}


#_______________________________________________________________________________
# CONNECTION HANDLING

#' Connect to a postgreSQL database, using settings from a config file
#'
#' Connect to a postgreSQL database (other dialects trivial).
#' Connection settings are loaded from a config file, content such as
#'     [profile-name]
#'     host = localhost
#'     port = 5439
#'     user = test
#'     database = playground
#'     password = <the password you entered IN PLAIN TEXT>
#' The connection parameters can be overwritten by optional function arguments.
#' The purpose of overwriting is simplified handling of multiple connections.
#' Default port 5439 is used if no port is configured or provided.
#' Config file may have different sections (=profiles); if none is chosen, the first
#' must do.
#' Connections will gracefully close upon termination of the R session, by
#' registration of a "finalizer".
#'
#' @param config_filepath the path to the config file
#' @param profile config section header (configs with multiple connection settings)
#' @param host the database server (usually an IP address)
#' @param port the port on which the host serves postgreSQL, default 5439
#' @param user the database username
#' @param password the users database password,
#'        hint1: use keyring::key_set("DBPassword", "db_user_password")
#'
#' @examples
#' \dontrun{
#'     keyring::key_set("DBPassword", "db_user_password") # prompt/store password
#'     config_filepath <- file.path("./server.conf")
#'     db_source <- connect_database_configfile(
#'       config_filepath, # sort of provides default settings
#'       database = "loceval",
#'       profile = "inbopostgis-dev",
#'       user = "panoramix" # override user
#'     )
#' }
#'
connect_database_configfile <- function(
    config_filepath,
    database = NULL,
    profile = NULL,
    host = NULL,
    port = NULL,
    user = NULL,
    password = NULL
    ) {
  # connect to a database, via config file
  # but settings can be overwritten upon function call

  # make sure config file exists
  stopifnot(file.exists(config_filepath))

  # profile (section within the config file)
  if (is.null(profile)) {
    profile <- 1 # use the first profile by default
  }

  # read connection info from a config file
  config <- configr::read.config(file = config_filepath)[[profile]]

  if (is.null(host)) {
    stopifnot("host" %in% attributes(config)$names)
    host <- config$host
  }

  if (is.null(port)) {
    if ("port" %in% attributes(config)$names) {
      port <- config$port
    } else {
      port <- 5439
    }
  }

  if (is.null(database)) {
    stopifnot("database" %in% attributes(config)$names)
    database <- config$database
  }

  if (is.null(user)) {
    stopifnot("user" %in% attributes(config)$names)
    user <- config$user
  }

  # store a label for verbose disconnection at exit
  db_label <- sprintf("%s@%s/%s", user, host, database)

  # get password.
  # (1) direct function input
  # (2) from config file
  # (3) user input
  if (is.null(password)) {
    if (is.null(config[["password"]])){
      if (keyring::key_get("DBPassword", "db_user_password") == "") {
        keyring::key_set("DBPassword", "db_user_password")
      }
      password <- keyring::key_get("DBPassword", "db_user_password")
    } else {
      password <- config$password
    }
  }

  # connect to database
  #
  tryCatch({
    if (is.na(password)) {
      database_connection <- DBI::dbConnect(
        RPostgres::Postgres(),
        dbname = database,
        host = host,
        port = port,
        user = user
      )
    } else {
      database_connection <- DBI::dbConnect(
        RPostgres::Postgres(),
        dbname = database,
        host = host,
        port = port,
        user = user,
        password = password
      )
    }
    },
    error = function(wrnmsg) {
      message(
        sprintf(
          'no password provided for connection %s. \n Try `keyring::key_set("DBPassword", "db_user_password")`.',
          db_label)
      )
    }
  )


  # remove the config: we do not want to expose credentials further
  # down in this notebook
  rm(config)

  # register disconnect for finalization
  # https://stackoverflow.com/a/41179916
  reg.finalizer(
    .GlobalEnv,
    function(e){
      DBI::dbDisconnect(database_connection)
      message(sprintf("Database %s gracefully disconnected.", db_label))
    },
    onexit = TRUE
  )

  return(invisible(database_connection))
} # /connect_database_configfile


#_______________________________________________________________________________
# DATABASE WORKHORSE

#' Connect to an MNM database by config and mirror.
#'
#' Connect to an MNM postgreSQL database.
#' Just requires a config file and a mirror.
#' The returned object is feature-rich, bringing all required
#' lookup-tables and functions.
#'
#' @param config_filepath the path to the config file
#' @param database_mirror database and mirror (equal to "config profile")
#' @param ... further connection parameters, forwarded to connect_database_configfile
#'
connect_mnm_database <- function(
    config_filepath,
    database_mirror = NA,
    skip_structure_assembly = FALSE ,
    ...
  ) {
  # database_mirror <- "mnmgwdb-staging"

  stopifnot(
    "glue" = require("glue"),
    "DBI" = require("DBI"),
    "keyring" = require("keyring"),
    "configr" = require("configr")
  )
  stopifnot("provide database mirror" = isFALSE(is.na(mirror)))

  # collect db connection
  db <- list()
  db$connection_profile <- database_mirror

  # load profile
  config <- configr::read.config(file = config_filepath)[[db$connection_profile]]

  for (cfg in attributes(config)$names) {
    if (cfg == "password") next
    db[[cfg]] <- config[[cfg]]
  }

  # connect
  db$connection <- connect_database_configfile(
    config_filepath,
    profile = database_mirror,
    database = config$database
  )
  if ("database" %in% attributes(config)$names) {
    db$connection <- connect_database_configfile(
      config_filepath,
      profile = database_mirror,
      database = config$database,
      ...
    )
  } else {
    db$connection <- connect_database_configfile(
      config_filepath,
      profile = database_mirror,
      ...
    )
  }

  # extend
  if (isFALSE(skip_structure_assembly)) {
    db <- mnmdb_assemble_structure_lookups(db)
    db <- mnmdb_assemble_query_functions(db)
  }

  return(db)
} # /connect_mnm_database


# take a database object and give it some structure
mnmdb_assemble_structure_lookups <- function(db) {

  # tables and their relations
  db$tables <- read.csv(here::here(db$folder, "TABLES.csv")) %>%
    select(table, schema, geometry, excluded)

  # this one is created by python scripts
  db$table_relations <- read_table_relations_config(
    storage_filepath = here::here(db$folder, "table_relations.conf")
    )

  # some tables are excluded
  db$excluded_tables <- db$tables %>%
    filter(!is.na(excluded)) %>%
    filter(excluded == 1) %>%
    pull(table)

  # get schema for a table
  db$get_schema <- function(table_label) {
    return(
      schemas %>%
        filter(table == table_label) %>%
        pull(schema)
    )
  }

  # get namestring as used in direct SQL queries
  db$get_namestring <- function(table_label) glue::glue('"{db$get_schema(table_label)}"."{table_label}"')

  # get table Id as used DBI/dbplyr queries
  db$get_tableid <- function(table_label) DBI::Id(schema = db$get_schema(table_label), table = table_label)

  ### table dependency structure
  db$get_dependent_tables <- function (table_key) {
    return(c(
      table_key,
      db$table_relations %>%
      filter(relation_table == tolower(table_key),
        !(dependent_table %in% db$excluded_tables)
      ) %>% pull(dependent_table)
    ))
  }

  # same as above, but from lowercase table key
  db$get_dbi_identifier_lowercase <- function(tabkey) {
    schema <- db$tables %>%
      filter(tolower(table) == tolower(tabkey)) %>%
      pull(schema)
    tkey_right <- schemas %>%
      filter(tolower(table) == tolower(tabkey)) %>%
      pull(table)
    return(DBI::Id(schema, tkey_right))
  }

  # return table IDs for all dependent tables
  db$get_dependent_table_ids <- function(table_key){
    return(lapply(
      db$get_dependent_tables(table_key),
      FUN = db$get_dbi_identifier_lowercase
    ))
  }

  # specific table info
  db$load_table_info <- function(table_label){
    table_info <- read.csv(
      here::here(db$folder, glue::glue("{table_label}.csv"))
    )
    return(table_info)
  }


  db$get_characteristic_columns <- function(table_label){

    # excluded from checks
    logging_columns <- c("log_user", "log_update", "geometry", "wkb_geometry")

    full_table_info <- db$load_table_info(table_label)

    pk <- full_table_info %>%
      filter(primary_key == "True") %>%
      pull(column)

    characteristic_columns <- full_table_info %>%
      filter(
        !(column %in% logging_columns),
        !(column %in% pk),
      ) %>%
      pull(column)

    return(characteristic_columns)
  }


  # or need a primary key?
  db$get_primary_key <- function(table_label) {
    return(
      db$load_table_info(table_label) %>%
        filter(primary_key == "True") %>%
        pull(column)
    )
  }

  # the result: a database object with more features
  return(db)
} # /mnmdb_assemble_structure_lookups


mnmdb_assemble_query_functions <- function(db) {

  db$query_columns <- function(table_label, select_columns){
    dplyr::tbl(db$connection, db$get_tableid(table_label)) %>%
      dplyr::select(!!!rlang::syms(select_columns)) %>%
      dplyr::collect()
  }

  db$is_spatial <- read.csv(here::here(dbstructure_folder, "TABLES.csv")) %>%
    select(table, geometry) %>%
    filter(tolower(table) == tolower(attr(table_id, "name")[[2]])) %>%
    pull(geometry) %>% is.na

  db$query_tbl <- function(table_label) {
    if (db$is_spatial(table_label)) {
      data <- sf::st_read(db_connection, table_id) %>% collect
    } else {
      data <- dplyr::tbl(db_connection, table_id) %>% collect
    }
    return(data)
  }

  # query_columns(db_connection, get_tableid(table_key), c("protocol_id", "description"))
  db$query_tables_data <- function(tables) {
    data <- lapply(
      tables,
      FUN =
    )
    return(data)
  }

  # all dependent lookup columns
  db$lookup_dependent_columns <- function(table_label, deptab_label) {

    # with a little help from my Python
    deptab_pk <- db$get_primary_key(deptab_label)

    # get the foreign key columns
    dependent_key <- db$table_relations %>%
      filter(
        relation_table == tolower(table_label),
        dependent_table == deptab_label
      ) %>%
      pull(dependent_column)

    # lookup the key columns
    key_lookup <- db$query_columns(
      deptab_label,
      c(deptab_pk, dependent_key)
    )

    return(key_lookup)
  }


  # temporarily store table and dependencies in memory
  db$store_table_deptree_in_memory <- function(table_label) {
    # savetabs <- find_dependent_tables("mnmgwdb_db_structure", "Visits")
    savetabs <- mnmdb$get_dependent_tables(table_label)

    return(
      lapply(
        savetabs,
        FUN = function(tablab) list(
          "label" = tablab,
          "data" = db$query_tbs(tablab)
        )
      )
    )
  }

  # direct execution
  db$execute_sql <- function(...) {return(execute_sql(db$connection, ...)}

  # push table from memory back to the server
  #   involves key resetting
  db$restore_table_data_from_memory <- function(table_content_storage, verbose = TRUE) {
    restore_ <- function(tabledata_list) {

      table_label <- tabledata_list$label
      schema <- db$get_schema(table_label)
      table_id <- db$get_tableid(table_label)
      table_data <- tabledata_list$data

      if (is.scalar.na(table_data) || (nrow(table_data) < 1)) {
        message("no data to restore.")
        return(invisible(NA))
      }

      # restore data
      pk <- db$get_primary_key(table_label)

      # Note that I neglect dependent table here, since they will be re-uploaded after
      ## delete from table
      db$execute_sql(
        glue::glue("DELETE FROM {table_label};"),
        verbose = verbose
      )

      ## reset the sequence
      sequence_key <- glue::glue('"{schema}".seq_{pk}')
      nextval_query <- glue::glue("SELECT last_value FROM {sequence_key};")

      current_highest <- DBI::dbGetQuery(db$connection, nextval_query)[[1, 1]]

      db$execute_sql(
        glue::glue('ALTER SEQUENCE {sequence_key} RESTART WITH 1;'),
        verbose = verbose
      )

      ## append the table data
      append_tabledata(db$connection, table_id, table_data)

      ## restore sequence
      nextval <- DBI::dbGetQuery(db$connection, nextval_query)[[1, 1]]
      nextval <- max(c(nextval, current_highest, table_data %>% pull(pk)))

      db$execute_sql(
        glue::glue("SELECT setval('{sequence_key}', {nextval});"),
        verbose = verbose
      )

      return(invisible(NULL))
    }

    # list-restore
    invisible(
      lapply(table_content_storage, FUN = restore_)
    )
  }



  return(db)

} # /mnmdb_assemble_query_functions


#_______________________________________________________________________________
# HANDLE BACKUPS

### TODO CONTINUE move this to db$ // mnmdb$

#' dump the database with a system call to `pg_dump` (linux)
#'
#' @details To apply this from scripts, password is not used. Make sure
#' to configure your `~/.pgpass` file.
#'
#' @param target_filepath the path to store the dump
#' @param config_filepath the path to the config file
#' @param database the database to backup
#' @param profile config section header (configs
#'        with multiple connection settings; best define a `dumpall`)
#' @param host the database server (usually an IP address)
#' @param port the port on which the host serves postgreSQL, default 5439
#' @param user the database username
#'
#' @examples
#' \dontrun{
#'   now <- format(Sys.time(), "%Y%m%d%H%M")
#'   dump_all(
#'     here::here(glue::glue("dumps/safedump_{now}.sql")),
#'     config_filepath = config_filepath,
#'     database = working_dbname,
#'     profile = "dumpall",
#'     user = "readonly_user",
#'     exclude_schema = c("tiger", "public")
#'   )
#' }
#'
dump_all <- function(
    target_filepath,
    config_filepath,
    database,
    profile = NULL,
    user = NULL,
    host = NULL,
    port = NULL,
    exclude_schema = NULL
    ) {

  stopifnot(
    "configr" = require("configr"),
    "glue" = require("glue"),
    "here" = require("here")
  )

  # profile (section within the config file)
  if (is.null(profile)) {
    profile <- 1 # use the first profile by default
  }

  # read connection info from a config file,
  # unless user provided different credentials
  config <- configr::read.config(file = config_filepath)[[profile]]

  if (is.null(host)) {
    stopifnot("host" %in% attributes(config)$names)
    host <- config$host
  }

  if (is.null(port)) {
    if ("port" %in% attributes(config)$names) {
      port <- config$port
    } else {
      port <- 5439
    }
  }

  if (is.null(user)) {
    stopifnot("user" %in% attributes(config)$names)
    user <- config$user
  }

  # exclude some schemas
  if (!is.null(exclude_schema)) {

    exschem_string <- c()
    for (exschem in exclude_schema){
      exschem_string <- c(exschem_string, glue::glue("-N {exschem}"))
    }
    exschem_string <- paste(exschem_string, collapse = " ")
  }

  # dump the database!
  dump_string <- glue::glue('
    pg_dump -U {user} -h {host} -p {port} -d {database} {exschem_string} --no-password > "{target_filepath}"
    ')

  system(dump_string)

} # /dump_all
