

* POC changes
** domain partition

introduced by Floris

#+begin_src sql
-- add domain part to loceval
-- ALTER TABLE "outbound"."FieldActivityCalendar" ADD COLUMN domain_part varchar;
-- COMMENT ON COLUMN "outbound"."FieldActivityCalendar".domain_part IS E'domain partition';
-- TODO is this an attribute of SampleUnits?


-- add domain part to mnmgwdb
ALTER TABLE "outbound"."SampleLocations" ADD COLUMN domain_part varchar;
COMMENT ON COLUMN "outbound"."SampleLocations".domain_part IS E'domain partition';

#+end_src

** TODO wait_<more>

more to wait

* FieldworkCalendar Needs `stratum`

finally, stratum comes to the gw database.

#+begin_src sql :eval no
ALTER TABLE "outbound"."FieldworkCalendar" ADD COLUMN stratum varchar DEFAULT NULL;
ALTER TABLE "inbound"."Visits" ADD COLUMN stratum varchar DEFAULT NULL;
ALTER TABLE "inbound"."WellInstallationActivities" ADD COLUMN stratum varchar DEFAULT NULL;
ALTER TABLE "inbound"."ChemicalSamplingActivities" ADD COLUMN stratum varchar DEFAULT NULL;
#+end_src


subprocedure: Stratum
>>> [[file:./20250909_FieldworkCalendar_Strata.R]]



* Versions
we now store the POC versions

subprocedure: Versions
>>> [[file:./20250908_Versions.sql]]


* Protocols

subprocedure: Protocols
>>> [[file:./20250904_Protocols.sql]]
>>> [[file:../views/gw_FieldWork.sql]]

-> MANUALLY update the Protocols table once.
>>> [[file:../070_update_POC.qmd]]

* column adjustments

teammember_id
date_visit
visit_done

#+begin_src sql :eval no
DROP VIEW IF EXISTS  "inbound"."FieldWork" CASCADE;
ALTER TABLE "inbound"."WellInstallationActivities" DROP COLUMN teammember_id;
ALTER TABLE "inbound"."ChemicalSamplingActivities" DROP COLUMN teammember_id;
ALTER TABLE "inbound"."WellInstallationActivities" DROP COLUMN date_visit;
ALTER TABLE "inbound"."ChemicalSamplingActivities" DROP COLUMN date_visit;
ALTER TABLE "inbound"."WellInstallationActivities" DROP COLUMN visit_done;
ALTER TABLE "inbound"."ChemicalSamplingActivities" DROP COLUMN visit_done;
#+end_src

+ + restore view!
  SELECT * FROM "inbound"."FieldWork" WHERE visit_done;

* Stitch Lookups

... to reduce off-focus updates during POC update

>>> [[file:../095_re_link_foreign_keys_optional.R]]


* POC update =v0.9.0_poc0.13.0=

# DELETE FROM "inbound"."Visits" WHERE grts_address = 871030 AND samplelocation_id = 857;

>>> [[file:../070_update_POC.qmd]]


* auxiliary maintenance scripts


* TODO

+ [✓] special activities upload
+ [✓] ++LocationInfos for new Locations
+ [✓] test =09*= update procedures
+ [ ] adjust filter 2026 locations
  + [ ] re-run all and check 871030
    SELECT * FROM "outbound"."FieldworkCalendar" WHERE grts_address = 871030 AND activity_group_id = 9 AND date_start = '2026-10-01';
+ [ ] adjust views
+ [ ] test qgis


* TODO Later

+ common reset =fieldwork_id=
+ what to do with "Visits".lims_code? (planning -> rename =_planned=?)
+ remove "LocationEvaluations".recovery_hints -> in =loceval=, link view to LocationInfos
+ rename SampleLocations -> SampleUnits
- sspstapas removed (NA) what to do with it? extend or drop?
- grts_join_method to SampleLocations?
