---
title: "Watershed: Toepassing op Vennen"
subtitle: "Catchment-gebieden."
date: "2025-11-27"
format:
  html:
    toc: true
    html-math-method: katex
    code-fold: false
    embed-resources: true
knitr:
  opts_chunk:
    echo: true
---


```{r libraries}
library("glue")
library("dplyr")
library("sf")
library("terra")
library("inbospatial")
library("mapview")

source(here::here("..", "R", "watershed.R"))
```

```{r read-shapefile}

shape_file_path <- "./voedingsgebieden/Selectie_Vennen.shp"
vennen <- sf::st_read(shape_file_path)
mapview::mapview(vennen)

```


Eventjes ééntje kiezen om te testen: het Zwarte Ven.

```{r testing}
testven <- vennen %>% filter(tolower(Veldnaam) == "mont noir")
test_centroid <- sf::st_geometry(testven) %>%
  sf::st_centroid() %>%
  sf::st_coordinates()
```


```{r assemble-data}
frame <- 512 # m
bbox <- sf::st_bbox(
   c(
     xmin = test_centroid[1] - frame,
     xmax = test_centroid[1] + frame,
     ymin = test_centroid[2] - frame,
     ymax = test_centroid[2] + frame
   ),
   crs = sf::st_crs(31370)
)

# query
test_raster <- inbospatial::get_coverage_wcs(
  wcs = "dhmv",
  bbox = bbox,
  layername = "DHMVII_DTM_1m",
  version = "2.0.1",
  wcs_crs = "EPSG:31370",
  resolution = 1
)

# smoothing
test_smoothed <- mdenoise(test_raster, n = 8, t = 0.6)

# if mdenoise is not available, try Gaussian:
# smooth_sigma <- 4 # range of pixels
# test_smoothed <- smooth_raster(test_raster, sigma = smooth_sigma)


# resampling
resample_width <- 16 # m grid cells
test_resampled <- resample_to_grid(
  test_smoothed,
  nrows = as.integer(dim(test_smoothed)[1]/resample_width),
  ncols = as.integer(dim(test_smoothed)[2]/resample_width)
)

smooth_sigma <- 4 # range of pixels
test_resampled <- smooth_raster(test_resampled, sigma = smooth_sigma)

# dim(test_resampled)

line <- sf::st_coordinates(testven)[, c(1,2)]
plot_testven_contour <- function() {
  lines(line[,1], line[,2])
}

par(mfrow = c(1,3))
plot(test_raster, col = gray.colors(256))
title("raw data")
plot_testven_contour()
points(test_centroid)
plot(test_smoothed, col = gray.colors(256))
title("smoothed")
plot_testven_contour()
points(test_centroid)
plot(test_resampled, col = gray.colors(256))
title(glue::glue("resampled ({resample_width} m cells)"))
plot_testven_contour()
points(test_centroid)
```



```{r masked-watershed}

raster_polygon <- terra::rast(testven, res = 1.0)
raster_class <- raster::rasterize(vect(testven), test_smoothed, "Id")
raster_mask <- deepcopy(test_smoothed)
raster_mask[] <- !is.na(as.matrix(raster_class, wide = TRUE))

mask_resampled <- resample_to_grid(
  raster_mask,
  nrows = dim(test_resampled)[1],
  ncols = dim(test_resampled)[2]
)
mask_resampled[] <- as.matrix(mask_resampled, wide = TRUE) > 0.05
# plot(mask_resampled)

test_mask <- as.matrix(mask_resampled, wide = TRUE)

test_ws <- compute_watershed(test_resampled)
test_ws_drained <- compute_watershed_drained(
  test_resampled,
  test_mask
)
# spat_raster <- test_smoothed


plot_points <- function(ws, ...) {
  sinks <- ws[["sinks"]]
  points(sinks[["x"]], sinks[["y"]], ...)
}


par(mfrow = c(2, 2))
plot(test_resampled, col = gray.colors(256))
title("resampled data")
plot_points(test_ws, col = "lightblue", pch = 17)
plot_points(test_ws_drained, col = "orange", pch = 22)
plot_testven_contour()
plot(test_ws[["watershed"]])
title("regular watershed")
plot_testven_contour()
plot_points(test_ws, col = "lightblue", pch = 17)
plot(raster_mask, col = rev(gray.colors(256)))
title("mask")
plot_testven_contour()
plot(test_ws_drained[["watershed"]])
title("masked watershed")
plot_testven_contour()
plot_points(test_ws_drained, col = "orange", pch = 15)

```


Code:
<https://github.com/inbo/n2khab-mne-monitoring/tree/shift_water_samples/010_aq_piezometer_positioning>

files: 

- `210_test_watershed.qmd`
- `211_vennen_watershed.qmd`

```{r}
sessionInfo()
```
