[Versions]

[Protocols]

[GroupedActivities]
protocols = ('protocol_id', 'protocol_id')

[TeamMembers]

[N2kHabStrata]

[Locations]

[LocationCells]
locations = ('location_id', 'location_id')

[Coordinates]
locations = ('location_id', 'location_id')

[LocationInfos]
locations = ('location_id', 'location_id')

[LocationJournals]
locations = ('location_id', 'location_id')

[SampleUnits]
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[LocationEvaluations]

[CellMaps]

[FieldCalendar]
teammembers = ('teammember_assigned', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[AllVisits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[Visits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[SamplingVisits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[InstallationRemovals]
locations = ('location_id', 'location_id')

[MHQPolygons]
locations = ('location_id', 'location_id')

[FreeFieldNotes]
teammembers = ('teammember_id', 'teammember_id')

[FieldFollowUps]
teammembers = ('teammember_id', 'teammember_id')

[ReplacementData]

