[Versions]

[Protocols]

[GroupedActivities]
protocols = ('protocol_id', 'protocol_id')
versions = ('archive_version_id', 'version_id')

[TeamMembers]

[N2kHabStrata]

[Locations]

[LocationCells]
locations = ('location_id', 'location_id')

[Coordinates]
locations = ('location_id', 'location_id')

[LocationInfos]
locations = ('location_id', 'location_id')

[LocationJournals]
locations = ('location_id', 'location_id')

[SampleUnits]
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[FieldCalendar]
teammembers = ('teammember_assigned', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[MHQPolygons]
locations = ('location_id', 'location_id')

[Visits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[OtherVisits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[LenticVisits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[LoticVisits]
fieldcalendar = ('fieldcalendar_id', 'fieldcalendar_id')
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[SamplingPoints]

[Observations]

[MeteorolObservations]

[GeoObservations]

[TerraBioObservations]

[AquaBioObservations]

[PerturbationObservations]

[LanduseObservations]

[FreeFieldNotes]
teammembers = ('teammember_id', 'teammember_id')

[FieldFollowUps]
teammembers = ('teammember_id', 'teammember_id')

[LocationEvaluations]

[CellMaps]

[TargetPoints]

[ReplacementData]

