[Versions]

[Protocols]

[GroupedActivities]
protocols = ('protocol_id', 'protocol_id')
versions = ('archive_version_id', 'version_id')

[TeamMembers]

[N2kHabStrata]

[Locations]

[LocationCells]
locations = ('location_id', 'location_id')

[Coordinates]
locations = ('location_id', 'location_id')

[LocationInfos]
locations = ('location_id', 'location_id')

[LocationJournals]
locations = ('location_id', 'location_id')

[SampleUnits]
locations = ('location_id', 'location_id')
versions = ('archive_version_id', 'version_id')

[SampleUnitPolygons]
sampleunits = ('sampleunit_id', 'sampleunit_id')

[Visits]
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[FieldCalendars]
visits = ('visit_id', 'visit_id')
teammembers = ('teammember_assigned', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[MHQPolygons]
locations = ('location_id', 'location_id')

[OtherVisits]
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[LenticVisits]
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[LoticVisits]
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')
versions = ('archive_version_id', 'version_id')

[ChlorophyllMeasurements]
locations = ('location_id', 'location_id')
teammembers = ('teammember_id', 'teammember_id')

[SamplingPoints]

[ElevationPoints]

[Observations]

[SampleContextObservations]

[PerturbationObservations]

[MeteorolObservations]

[GeoObservations]

[TerraBioObservations]

[AquaBioObservations]

[LanduseObservations]

[FreeFieldNotes]
teammembers = ('teammember_id', 'teammember_id')

[Trails]

[FieldFollowUps]
teammembers = ('teammember_id', 'teammember_id')

[LocationEvaluations]

[CellMaps]

[TargetPoints]

[ReplacementData]

